/* tslint:disable */
/* eslint-disable */
/**
 * Географические объекты
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { AsyncResultOutput } from './AsyncResultOutput';
import {
    AsyncResultOutputFromJSON,
    AsyncResultOutputFromJSONTyped,
    AsyncResultOutputToJSON,
} from './AsyncResultOutput';

/**
 * 
 * @export
 * @interface ApiAsyncResultPut200Response
 */
export interface ApiAsyncResultPut200Response {
    /**
     * 
     * @type {string}
     * @memberof ApiAsyncResultPut200Response
     */
    message?: string;
    /**
     * 
     * @type {AsyncResultOutput}
     * @memberof ApiAsyncResultPut200Response
     */
    data?: AsyncResultOutput;
}

/**
 * Check if a given object implements the ApiAsyncResultPut200Response interface.
 */
export function instanceOfApiAsyncResultPut200Response(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ApiAsyncResultPut200ResponseFromJSON(json: any): ApiAsyncResultPut200Response {
    return ApiAsyncResultPut200ResponseFromJSONTyped(json, false);
}

export function ApiAsyncResultPut200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiAsyncResultPut200Response {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'message': !exists(json, 'message') ? undefined : json['message'],
        'data': !exists(json, 'data') ? undefined : AsyncResultOutputFromJSON(json['data']),
    };
}

export function ApiAsyncResultPut200ResponseToJSON(value?: ApiAsyncResultPut200Response | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'message': value.message,
        'data': AsyncResultOutputToJSON(value.data),
    };
}

