/* tslint:disable */
/* eslint-disable */
/**
 * Географические объекты
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { GeographicalObjectSerializer } from './GeographicalObjectSerializer';
import {
    GeographicalObjectSerializerFromJSON,
    GeographicalObjectSerializerFromJSONTyped,
    GeographicalObjectSerializerToJSON,
} from './GeographicalObjectSerializer';
import type { LocationSerializer } from './LocationSerializer';
import {
    LocationSerializerFromJSON,
    LocationSerializerFromJSONTyped,
    LocationSerializerToJSON,
} from './LocationSerializer';

/**
 * 
 * @export
 * @interface ApiGeographicalObjectIdCreateServiceInTaskPost201Response
 */
export interface ApiGeographicalObjectIdCreateServiceInTaskPost201Response {
    /**
     * 
     * @type {string}
     * @memberof ApiGeographicalObjectIdCreateServiceInTaskPost201Response
     */
    message?: string;
    /**
     * 
     * @type {number}
     * @memberof ApiGeographicalObjectIdCreateServiceInTaskPost201Response
     */
    idDraft?: number;
    /**
     * 
     * @type {Array<GeographicalObjectSerializer>}
     * @memberof ApiGeographicalObjectIdCreateServiceInTaskPost201Response
     */
    geographicalObject?: Array<GeographicalObjectSerializer>;
    /**
     * 
     * @type {Array<LocationSerializer>}
     * @memberof ApiGeographicalObjectIdCreateServiceInTaskPost201Response
     */
    location?: Array<LocationSerializer>;
}

/**
 * Check if a given object implements the ApiGeographicalObjectIdCreateServiceInTaskPost201Response interface.
 */
export function instanceOfApiGeographicalObjectIdCreateServiceInTaskPost201Response(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ApiGeographicalObjectIdCreateServiceInTaskPost201ResponseFromJSON(json: any): ApiGeographicalObjectIdCreateServiceInTaskPost201Response {
    return ApiGeographicalObjectIdCreateServiceInTaskPost201ResponseFromJSONTyped(json, false);
}

export function ApiGeographicalObjectIdCreateServiceInTaskPost201ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiGeographicalObjectIdCreateServiceInTaskPost201Response {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'message': !exists(json, 'message') ? undefined : json['message'],
        'idDraft': !exists(json, 'id_draft') ? undefined : json['id_draft'],
        'geographicalObject': !exists(json, 'geographical_object') ? undefined : ((json['geographical_object'] as Array<any>).map(GeographicalObjectSerializerFromJSON)),
        'location': !exists(json, 'location') ? undefined : ((json['location'] as Array<any>).map(LocationSerializerFromJSON)),
    };
}

export function ApiGeographicalObjectIdCreateServiceInTaskPost201ResponseToJSON(value?: ApiGeographicalObjectIdCreateServiceInTaskPost201Response | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'message': value.message,
        'id_draft': value.idDraft,
        'geographical_object': value.geographicalObject === undefined ? undefined : ((value.geographicalObject as Array<any>).map(GeographicalObjectSerializerToJSON)),
        'location': value.location === undefined ? undefined : ((value.location as Array<any>).map(LocationSerializerToJSON)),
    };
}

