/* tslint:disable */
/* eslint-disable */
/**
 * Географические объекты
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ApiLocationIdLocationMarsStationIdMarsStationUpdatePutRequest
 */
export interface ApiLocationIdLocationMarsStationIdMarsStationUpdatePutRequest {
    /**
     * 
     * @type {string}
     * @memberof ApiLocationIdLocationMarsStationIdMarsStationUpdatePutRequest
     */
    direction: string;
}

/**
 * Check if a given object implements the ApiLocationIdLocationMarsStationIdMarsStationUpdatePutRequest interface.
 */
export function instanceOfApiLocationIdLocationMarsStationIdMarsStationUpdatePutRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "direction" in value;

    return isInstance;
}

export function ApiLocationIdLocationMarsStationIdMarsStationUpdatePutRequestFromJSON(json: any): ApiLocationIdLocationMarsStationIdMarsStationUpdatePutRequest {
    return ApiLocationIdLocationMarsStationIdMarsStationUpdatePutRequestFromJSONTyped(json, false);
}

export function ApiLocationIdLocationMarsStationIdMarsStationUpdatePutRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiLocationIdLocationMarsStationIdMarsStationUpdatePutRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'direction': json['direction'],
    };
}

export function ApiLocationIdLocationMarsStationIdMarsStationUpdatePutRequestToJSON(value?: ApiLocationIdLocationMarsStationIdMarsStationUpdatePutRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'direction': value.direction,
    };
}

