/* tslint:disable */
/* eslint-disable */
/**
 * Географические объекты
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { GeographicalObjectSerializer } from './GeographicalObjectSerializer';
import {
    GeographicalObjectSerializerFromJSON,
    GeographicalObjectSerializerFromJSONTyped,
    GeographicalObjectSerializerToJSON,
} from './GeographicalObjectSerializer';
import type { LocationSerializer } from './LocationSerializer';
import {
    LocationSerializerFromJSON,
    LocationSerializerFromJSONTyped,
    LocationSerializerToJSON,
} from './LocationSerializer';

/**
 * 
 * @export
 * @interface ApiLocationIdLocationMarsStationIdMarsStationUpdatePut200Response
 */
export interface ApiLocationIdLocationMarsStationIdMarsStationUpdatePut200Response {
    /**
     * 
     * @type {string}
     * @memberof ApiLocationIdLocationMarsStationIdMarsStationUpdatePut200Response
     */
    message?: string;
    /**
     * 
     * @type {LocationSerializer}
     * @memberof ApiLocationIdLocationMarsStationIdMarsStationUpdatePut200Response
     */
    location?: LocationSerializer;
    /**
     * 
     * @type {GeographicalObjectSerializer}
     * @memberof ApiLocationIdLocationMarsStationIdMarsStationUpdatePut200Response
     */
    geographicalObject?: GeographicalObjectSerializer;
}

/**
 * Check if a given object implements the ApiLocationIdLocationMarsStationIdMarsStationUpdatePut200Response interface.
 */
export function instanceOfApiLocationIdLocationMarsStationIdMarsStationUpdatePut200Response(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ApiLocationIdLocationMarsStationIdMarsStationUpdatePut200ResponseFromJSON(json: any): ApiLocationIdLocationMarsStationIdMarsStationUpdatePut200Response {
    return ApiLocationIdLocationMarsStationIdMarsStationUpdatePut200ResponseFromJSONTyped(json, false);
}

export function ApiLocationIdLocationMarsStationIdMarsStationUpdatePut200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiLocationIdLocationMarsStationIdMarsStationUpdatePut200Response {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'message': !exists(json, 'message') ? undefined : json['message'],
        'location': !exists(json, 'location') ? undefined : LocationSerializerFromJSON(json['location']),
        'geographicalObject': !exists(json, 'geographical_object') ? undefined : GeographicalObjectSerializerFromJSON(json['geographical_object']),
    };
}

export function ApiLocationIdLocationMarsStationIdMarsStationUpdatePut200ResponseToJSON(value?: ApiLocationIdLocationMarsStationIdMarsStationUpdatePut200Response | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'message': value.message,
        'location': LocationSerializerToJSON(value.location),
        'geographical_object': GeographicalObjectSerializerToJSON(value.geographicalObject),
    };
}

