/* tslint:disable */
/* eslint-disable */
/**
 * Географические объекты
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AsyncResultOutput
 */
export interface AsyncResultOutput {
    /**
     * 
     * @type {number}
     * @memberof AsyncResultOutput
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof AsyncResultOutput
     */
    statusTask?: string;
    /**
     * 
     * @type {string}
     * @memberof AsyncResultOutput
     */
    statusMission?: string;
}

/**
 * Check if a given object implements the AsyncResultOutput interface.
 */
export function instanceOfAsyncResultOutput(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function AsyncResultOutputFromJSON(json: any): AsyncResultOutput {
    return AsyncResultOutputFromJSONTyped(json, false);
}

export function AsyncResultOutputFromJSONTyped(json: any, ignoreDiscriminator: boolean): AsyncResultOutput {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'statusTask': !exists(json, 'status_task') ? undefined : json['status_task'],
        'statusMission': !exists(json, 'status_mission') ? undefined : json['status_mission'],
    };
}

export function AsyncResultOutputToJSON(value?: AsyncResultOutput | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'status_task': value.statusTask,
        'status_mission': value.statusMission,
    };
}

