/* tslint:disable */
/* eslint-disable */
/**
 * Географические объекты
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface EmployeeRegister
 */
export interface EmployeeRegister {
    /**
     * 
     * @type {string}
     * @memberof EmployeeRegister
     */
    fullName: string;
    /**
     * 
     * @type {string}
     * @memberof EmployeeRegister
     */
    post: string;
    /**
     * 
     * @type {string}
     * @memberof EmployeeRegister
     */
    nameOrganization: string;
    /**
     * 
     * @type {string}
     * @memberof EmployeeRegister
     */
    address: string;
}

/**
 * Check if a given object implements the EmployeeRegister interface.
 */
export function instanceOfEmployeeRegister(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "fullName" in value;
    isInstance = isInstance && "post" in value;
    isInstance = isInstance && "nameOrganization" in value;
    isInstance = isInstance && "address" in value;

    return isInstance;
}

export function EmployeeRegisterFromJSON(json: any): EmployeeRegister {
    return EmployeeRegisterFromJSONTyped(json, false);
}

export function EmployeeRegisterFromJSONTyped(json: any, ignoreDiscriminator: boolean): EmployeeRegister {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'fullName': json['full_name'],
        'post': json['post'],
        'nameOrganization': json['name_organization'],
        'address': json['address'],
    };
}

export function EmployeeRegisterToJSON(value?: EmployeeRegister | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'full_name': value.fullName,
        'post': value.post,
        'name_organization': value.nameOrganization,
        'address': value.address,
    };
}

