/* tslint:disable */
/* eslint-disable */
/**
 * Географические объекты
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Employee
 */
export interface Employee {
    /**
     * 
     * @type {number}
     * @memberof Employee
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof Employee
     */
    fullName: string;
    /**
     * 
     * @type {string}
     * @memberof Employee
     */
    post: string;
    /**
     * 
     * @type {string}
     * @memberof Employee
     */
    nameOrganization: string;
    /**
     * 
     * @type {string}
     * @memberof Employee
     */
    address: string;
    /**
     * 
     * @type {number}
     * @memberof Employee
     */
    idUser: number;
}

/**
 * Check if a given object implements the Employee interface.
 */
export function instanceOfEmployee(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "fullName" in value;
    isInstance = isInstance && "post" in value;
    isInstance = isInstance && "nameOrganization" in value;
    isInstance = isInstance && "address" in value;
    isInstance = isInstance && "idUser" in value;

    return isInstance;
}

export function EmployeeFromJSON(json: any): Employee {
    return EmployeeFromJSONTyped(json, false);
}

export function EmployeeFromJSONTyped(json: any, ignoreDiscriminator: boolean): Employee {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'fullName': json['full_name'],
        'post': json['post'],
        'nameOrganization': json['name_organization'],
        'address': json['address'],
        'idUser': json['id_user'],
    };
}

export function EmployeeToJSON(value?: Employee | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'full_name': value.fullName,
        'post': value.post,
        'name_organization': value.nameOrganization,
        'address': value.address,
        'id_user': value.idUser,
    };
}

