/* tslint:disable */
/* eslint-disable */
/**
 * Географические объекты
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface EmployeeSerializer
 */
export interface EmployeeSerializer {
    /**
     * 
     * @type {number}
     * @memberof EmployeeSerializer
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof EmployeeSerializer
     */
    fullName?: string;
    /**
     * 
     * @type {string}
     * @memberof EmployeeSerializer
     */
    post?: string;
    /**
     * 
     * @type {string}
     * @memberof EmployeeSerializer
     */
    nameOrganization?: string;
    /**
     * 
     * @type {string}
     * @memberof EmployeeSerializer
     */
    address?: string;
    /**
     * 
     * @type {number}
     * @memberof EmployeeSerializer
     */
    idUser?: number;
}

/**
 * Check if a given object implements the EmployeeSerializer interface.
 */
export function instanceOfEmployeeSerializer(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function EmployeeSerializerFromJSON(json: any): EmployeeSerializer {
    return EmployeeSerializerFromJSONTyped(json, false);
}

export function EmployeeSerializerFromJSONTyped(json: any, ignoreDiscriminator: boolean): EmployeeSerializer {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'fullName': !exists(json, 'full_name') ? undefined : json['full_name'],
        'post': !exists(json, 'post') ? undefined : json['post'],
        'nameOrganization': !exists(json, 'name_organization') ? undefined : json['name_organization'],
        'address': !exists(json, 'address') ? undefined : json['address'],
        'idUser': !exists(json, 'id_user') ? undefined : json['id_user'],
    };
}

export function EmployeeSerializerToJSON(value?: EmployeeSerializer | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'full_name': value.fullName,
        'post': value.post,
        'name_organization': value.nameOrganization,
        'address': value.address,
        'id_user': value.idUser,
    };
}

