/* tslint:disable */
/* eslint-disable */
/**
 * Географические объекты
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { GeographicalObjectSerializer } from './GeographicalObjectSerializer';
import {
    GeographicalObjectSerializerFromJSON,
    GeographicalObjectSerializerFromJSONTyped,
    GeographicalObjectSerializerToJSON,
} from './GeographicalObjectSerializer';

/**
 * 
 * @export
 * @interface GeographicalObjectListSerializer
 */
export interface GeographicalObjectListSerializer {
    /**
     * 
     * @type {number}
     * @memberof GeographicalObjectListSerializer
     */
    count: number;
    /**
     * 
     * @type {number}
     * @memberof GeographicalObjectListSerializer
     */
    idDraftService?: number;
    /**
     * 
     * @type {number}
     * @memberof GeographicalObjectListSerializer
     */
    countGeographicalObjectByDraft?: number;
    /**
     * 
     * @type {Array<GeographicalObjectSerializer>}
     * @memberof GeographicalObjectListSerializer
     */
    results: Array<GeographicalObjectSerializer>;
}

/**
 * Check if a given object implements the GeographicalObjectListSerializer interface.
 */
export function instanceOfGeographicalObjectListSerializer(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "count" in value;
    isInstance = isInstance && "results" in value;

    return isInstance;
}

export function GeographicalObjectListSerializerFromJSON(json: any): GeographicalObjectListSerializer {
    return GeographicalObjectListSerializerFromJSONTyped(json, false);
}

export function GeographicalObjectListSerializerFromJSONTyped(json: any, ignoreDiscriminator: boolean): GeographicalObjectListSerializer {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'count': json['count'],
        'idDraftService': !exists(json, 'id_draft_service') ? undefined : json['id_draft_service'],
        'countGeographicalObjectByDraft': !exists(json, 'count_geographical_object_by_draft') ? undefined : json['count_geographical_object_by_draft'],
        'results': ((json['results'] as Array<any>).map(GeographicalObjectSerializerFromJSON)),
    };
}

export function GeographicalObjectListSerializerToJSON(value?: GeographicalObjectListSerializer | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'count': value.count,
        'id_draft_service': value.idDraftService,
        'count_geographical_object_by_draft': value.countGeographicalObjectByDraft,
        'results': ((value.results as Array<any>).map(GeographicalObjectSerializerToJSON)),
    };
}

