/* tslint:disable */
/* eslint-disable */
/**
 * Географические объекты
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface LocationSerializer
 */
export interface LocationSerializer {
    /**
     * 
     * @type {number}
     * @memberof LocationSerializer
     */
    id?: number;
    /**
     * 
     * @type {number}
     * @memberof LocationSerializer
     */
    sequenceNumber?: number;
    /**
     * 
     * @type {number}
     * @memberof LocationSerializer
     */
    idGeographicalObject?: number;
    /**
     * 
     * @type {number}
     * @memberof LocationSerializer
     */
    idMarsStation?: number;
}

/**
 * Check if a given object implements the LocationSerializer interface.
 */
export function instanceOfLocationSerializer(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function LocationSerializerFromJSON(json: any): LocationSerializer {
    return LocationSerializerFromJSONTyped(json, false);
}

export function LocationSerializerFromJSONTyped(json: any, ignoreDiscriminator: boolean): LocationSerializer {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'sequenceNumber': !exists(json, 'sequence_number') ? undefined : json['sequence_number'],
        'idGeographicalObject': !exists(json, 'id_geographical_object') ? undefined : json['id_geographical_object'],
        'idMarsStation': !exists(json, 'id_mars_station') ? undefined : json['id_mars_station'],
    };
}

export function LocationSerializerToJSON(value?: LocationSerializer | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'sequence_number': value.sequenceNumber,
        'id_geographical_object': value.idGeographicalObject,
        'id_mars_station': value.idMarsStation,
    };
}

