/* tslint:disable */
/* eslint-disable */
/**
 * Географические объекты
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PUTMarsStationBYADMINRequest
 */
export interface PUTMarsStationBYADMINRequest {
    /**
     * 
     * @type {number}
     * @memberof PUTMarsStationBYADMINRequest
     */
    statusTask: number;
}

/**
 * Check if a given object implements the PUTMarsStationBYADMINRequest interface.
 */
export function instanceOfPUTMarsStationBYADMINRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "statusTask" in value;

    return isInstance;
}

export function PUTMarsStationBYADMINRequestFromJSON(json: any): PUTMarsStationBYADMINRequest {
    return PUTMarsStationBYADMINRequestFromJSONTyped(json, false);
}

export function PUTMarsStationBYADMINRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): PUTMarsStationBYADMINRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'statusTask': json['status_task'],
    };
}

export function PUTMarsStationBYADMINRequestToJSON(value?: PUTMarsStationBYADMINRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'status_task': value.statusTask,
    };
}

