/* tslint:disable */
/* eslint-disable */
/**
 * Географические объекты
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TypeTransportSerializerIDTYPE
 */
export interface TypeTransportSerializerIDTYPE {
    /**
     * 
     * @type {number}
     * @memberof TypeTransportSerializerIDTYPE
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof TypeTransportSerializerIDTYPE
     */
    type?: string;
}

/**
 * Check if a given object implements the TypeTransportSerializerIDTYPE interface.
 */
export function instanceOfTypeTransportSerializerIDTYPE(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function TypeTransportSerializerIDTYPEFromJSON(json: any): TypeTransportSerializerIDTYPE {
    return TypeTransportSerializerIDTYPEFromJSONTyped(json, false);
}

export function TypeTransportSerializerIDTYPEFromJSONTyped(json: any, ignoreDiscriminator: boolean): TypeTransportSerializerIDTYPE {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'type': !exists(json, 'type') ? undefined : json['type'],
    };
}

export function TypeTransportSerializerIDTYPEToJSON(value?: TypeTransportSerializerIDTYPE | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'type': value.type,
    };
}

