/* tslint:disable */
/* eslint-disable */
/**
 * Географические объекты
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UsersRegister
 */
export interface UsersRegister {
    /**
     * 
     * @type {string}
     * @memberof UsersRegister
     */
    username: string;
    /**
     * 
     * @type {string}
     * @memberof UsersRegister
     */
    password: string;
    /**
     * 
     * @type {boolean}
     * @memberof UsersRegister
     */
    isModerator: boolean;
}

/**
 * Check if a given object implements the UsersRegister interface.
 */
export function instanceOfUsersRegister(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "username" in value;
    isInstance = isInstance && "password" in value;
    isInstance = isInstance && "isModerator" in value;

    return isInstance;
}

export function UsersRegisterFromJSON(json: any): UsersRegister {
    return UsersRegisterFromJSONTyped(json, false);
}

export function UsersRegisterFromJSONTyped(json: any, ignoreDiscriminator: boolean): UsersRegister {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'username': json['username'],
        'password': json['password'],
        'isModerator': json['is_moderator'],
    };
}

export function UsersRegisterToJSON(value?: UsersRegister | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'username': value.username,
        'password': value.password,
        'is_moderator': value.isModerator,
    };
}

