/* tslint:disable */
/* eslint-disable */
/**
 * Географические объекты
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { EmployeeRegister } from './EmployeeRegister';
import {
    EmployeeRegisterFromJSON,
    EmployeeRegisterFromJSONTyped,
    EmployeeRegisterToJSON,
} from './EmployeeRegister';
import type { UsersRegister } from './UsersRegister';
import {
    UsersRegisterFromJSON,
    UsersRegisterFromJSONTyped,
    UsersRegisterToJSON,
} from './UsersRegister';

/**
 * 
 * @export
 * @interface UserRegisterSerializer
 */
export interface UserRegisterSerializer {
    /**
     * 
     * @type {UsersRegister}
     * @memberof UserRegisterSerializer
     */
    user: UsersRegister;
    /**
     * 
     * @type {EmployeeRegister}
     * @memberof UserRegisterSerializer
     */
    employee: EmployeeRegister;
}

/**
 * Check if a given object implements the UserRegisterSerializer interface.
 */
export function instanceOfUserRegisterSerializer(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "user" in value;
    isInstance = isInstance && "employee" in value;

    return isInstance;
}

export function UserRegisterSerializerFromJSON(json: any): UserRegisterSerializer {
    return UserRegisterSerializerFromJSONTyped(json, false);
}

export function UserRegisterSerializerFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserRegisterSerializer {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'user': UsersRegisterFromJSON(json['user']),
        'employee': EmployeeRegisterFromJSON(json['employee']),
    };
}

export function UserRegisterSerializerToJSON(value?: UserRegisterSerializer | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'user': UsersRegisterToJSON(value.user),
        'employee': EmployeeRegisterToJSON(value.employee),
    };
}

