/* tslint:disable */
/* eslint-disable */
/**
 * Географические объекты
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ApiAsyncResultPut200Response,
  AsyncResultInput,
} from '../models/index';
import {
    ApiAsyncResultPut200ResponseFromJSON,
    ApiAsyncResultPut200ResponseToJSON,
    AsyncResultInputFromJSON,
    AsyncResultInputToJSON,
} from '../models/index';

export interface ApiAsyncResultPutRequest {
    asyncResultInput: AsyncResultInput;
}

/**
 * 
 */
export class AsynchronousServiceApi extends runtime.BaseAPI {

    /**
     * Изменяет результат асинхронной операции
     */
    async apiAsyncResultPutRaw(requestParameters: ApiAsyncResultPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ApiAsyncResultPut200Response>> {
        if (requestParameters.asyncResultInput === null || requestParameters.asyncResultInput === undefined) {
            throw new runtime.RequiredError('asyncResultInput','Required parameter requestParameters.asyncResultInput was null or undefined when calling apiAsyncResultPut.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/api/async_result/`,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: AsyncResultInputToJSON(requestParameters.asyncResultInput),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ApiAsyncResultPut200ResponseFromJSON(jsonValue));
    }

    /**
     * Изменяет результат асинхронной операции
     */
    async apiAsyncResultPut(requestParameters: ApiAsyncResultPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ApiAsyncResultPut200Response> {
        const response = await this.apiAsyncResultPutRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
