/* tslint:disable */
/* eslint-disable */
/**
 * Географические объекты
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  TypeTransportSerializerIDTYPE,
} from '../models/index';
import {
    TypeTransportSerializerIDTYPEFromJSON,
    TypeTransportSerializerIDTYPEToJSON,
} from '../models/index';

export interface ApiTransportGetRequest {
    type?: string;
}

/**
 * 
 */
export class TransportApi extends runtime.BaseAPI {

    /**
     * Получает список транспорта
     */
    async apiTransportGetRaw(requestParameters: ApiTransportGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<TypeTransportSerializerIDTYPE>>> {
        const queryParameters: any = {};

        if (requestParameters.type !== undefined) {
            queryParameters['type'] = requestParameters.type;
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/transport/`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(TypeTransportSerializerIDTYPEFromJSON));
    }

    /**
     * Получает список транспорта
     */
    async apiTransportGet(requestParameters: ApiTransportGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<TypeTransportSerializerIDTYPE>> {
        const response = await this.apiTransportGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
